_wandb:
    value:
        cli_version: 0.23.1
        e:
            2i6jw3lhorlatn42zqmwutp7ek9zhtpf:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: src/my_project/train.py
                codePathLocal: src/my_project/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "111006752768"
                email: nikosfergadakis@gmail.com
                executable: /opt/miniconda3/envs/mlops312/bin/python
                git:
                    commit: 1a4e8c9482b8075ea0d7bba2de38afbe55f6311d
                    remote: git@github.com:FergadakisN/ml_ops2.git
                host: 192.168.1.38
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/nikolaosfergadakis/Desktop/DTU/january_course/ml_ops/dtu_mlops2/my_project/src/my_project/train.py
                python: CPython 3.12.12
                root: /Users/nikolaosfergadakis/Desktop/DTU/january_course/ml_ops/dtu_mlops2/my_project
                startedAt: "2026-01-08T20:38:40.307355Z"
                writerId: 2i6jw3lhorlatn42zqmwutp7ek9zhtpf
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
